version: '4'

services:
  db:
    image: postgres:latest
    restart: always
#    hostname: db
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "orders"
#    ports:
#      - "5433:5432"
    volumes:
      - ./pq_scripts/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data

  orders:
    image: orders:latest
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: orders
    ports:
      - "8081:8081"
    depends_on:
      - db
