version: '4'

services:
  authdb:
    image: postgres:latest
    restart: always
#    hostname: db
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "auth"
    volumes:
      - ./auth/pq_scripts/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./auth/postgres-data:/var/lib/postgresql/data

  auth:
    image: auth:latest
    restart: always
    build:
      context: auth
      dockerfile: ./Dockerfile
    container_name: auth
    ports:
      - "8080:8080"
    depends_on:
      - authdb

  ordersdb:
    image: postgres:latest
    restart: always
    #    hostname: db
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "orders"
    #    ports:
    #      - "5433:5432"
    volumes:
      - ./orders/pq_scripts/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./orders/postgres-data:/var/lib/postgresql/data

  orders:
    image: orders:latest
    restart: always
    build:
      context: orders
      dockerfile: ./Dockerfile
    container_name: orders
    ports:
      - "8081:8081"
    depends_on:
      - ordersdb
